### PR TITLE
Fixed error when opening vim without a buffer

### PR DESCRIPTION
**Pull request by m42e**

### CODE REVIEW

**Comment by m42e** [comment]
Without that fix I get 

```
Error detected while processing function <SNR>64_Prosession:
line    7:
E85: There is no listed buffer
```
at startup

**Comment by dhruvasagar** [comment]
How do I reproduce this?

**Comment by m42e** [comment]
I simply go into a directory, where a session has been created previously and run ```vim```

**Comment by dhruvasagar** [comment]
I don't get that error. What version of vim are you using ?

**Comment by dhruvasagar** [comment]
Although I suppose the simpler fix (if this is an issue) would be to just use `:silent!` instead if `:silent`

**Comment by m42e** [comment]
Seems to be valid. ```silent!``` works.

**Comment by dhruvasagar** [comment]
Thanks

**Pull request merged**
