### PR TITLE
Fixed StripTrailingSlash

### PR DESCRIPTION
**Pull request by m42e**

### CODE REVIEW

**Comment by dhruvasagar** [comment]
Sorry for the goofup, was a typo.

**Comment by m42e** [comment]
removed the additional commit, which should have been in an extra branch.

**Comment by dhruvasagar** [comment]
It should be working now

**Comment by dhruvasagar** [comment]
What's the filter for exactly ?

**Comment by dhruvasagar** [comment]
I've already added this fix, thanks for your contribution.

**Pull request closed without merging**
